import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "./store/provider";
import Header from "./components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={"bg-[#607274]  text-white"}
        suppressHydrationWarning={true}
      >
        <ReduxProvider>
          <Header />

          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
