import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "./store/provider";
import Header from "./components/header";
import Cart from "./components/cart";
import SideNav from "./components/sideNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={"bg-[#001b4a] relative pb-[5rem] text-white"}
        suppressHydrationWarning={true}
      >
        <ReduxProvider>
          <Header />
          {children}
          <Cart />
        </ReduxProvider>
      </body>
    </html>
  );
}
